openapi. 3.0.3
info:
  title: UDisc Public API
  version: 0.0.0
  description: Reverse Engineered public API for UDisc

servers:
  - url: https://udisc.com

paths:
  /courses.data:
    get:
      summary: Get courses
      parameters:
        - name: sortOrder
          in: query
          description: Field to sort by
          required: false
          schema:
            type: string
            enum: [default, rating, dist]
      responses:
        '200':
          description: A list of disc golf courses

  /api/places/search:
    get:
      summary: Search for places
      parameters:
        - name: term
          in: query
          description: Term to search by
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: How many search results to return
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of places related to the search
